### ISSUE TITLE
Uninitialized variables with dump-dataflash

### ISSUE THREAD

**Issue by ReservedField** [Ban3/python-evic#1]
I've been experiencing problems with the last revision when using dump-dataflash:

```
$ sudo evic dump-dataflash -o a.bin

Found device:
    Manufacturer: Nuvoton
    Product: HID Transfer
    Serial No: XXXXXXXXXXXX

Traceback (most recent call last):
  File "/bin/evic", line 9, in <module>
    load_entry_point('evic==0.1', 'console_scripts', 'evic')()
  File "build/bdist.linux-x86_64/egg/evic/cli.py", line 93, in main
UnboundLocalError: local variable 'aprom' referenced before assignment
```

I'm attaching a patch that fixes the issue (also args.dataflash needs to be checked for existence as it won't be set with dump-dataflash). I don't know if I'm the only one having problems with it, but it shouldn't hurt anyway.
Renamed to .txt, otherwise Issues wouldn't let me upload it: [unbound-local-fix.txt](https://github.com/Ban3/python-evic/files/57156/unbound-local-fix.txt)

**Comment by ReservedField** [comment]
Ouch, found same bug in a different place. Here's a better fix: [unbound-local-fix-2.patch.txt](https://github.com/Ban3/python-evic/files/57234/unbound-local-fix-2.patch.txt)

**Comment by Ban3** [comment]
Thanks for the report.  This should now be fixed in master. Reopen if not.
